sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - SITE_URL=https://zendframework.github.io/zend-servicemanager-di
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL=matthew@weierophinney.net
    - GH_REF=github.com/zendframework/zend-servicemanager-di.git
    - secure: "LLQyY02oKjXOsoU++VOH9HPfKTunYZlMfPkHwLFPHBNop8TMWznKCJPokQVvN3sdQt/vFycKIJ22stIMnQ0w2C8KoZ+UJBWg4VwQSYbqJbPs4NV6zqPYhPuUwdZxmdFXo9kW4ZP6/HQgSIHEEguzcu/1EFtJDLZzFE8zxPctT7So1yZ0HZJFg/sYKg1fYN2PhYQ+2a8WiucuuixLv0qUFjf8eYzqMBse4r1r9CpibgeLuHGQctLkJtedbTbVdbHBusyNY2T6n02RnTjOkiFYJOMxl9DCELEz3hxhF1b6oasmu0N2B1Jdyux61nLvJwDhcILxbDxPUDx6xyqDjAYUvqHOaVC4V+9Ie3wK6u21xeiYqmJIkECZV5I9h8DYdufU37V5XO3zv++6gGMIJGaGPLu2kHdfKuwdGgQryRWkT71/nlR3H8W4YV6V4IWb+zl5zKfM847D4yadjwTm0B8Ko2zMWc5O4FdetltM4H83jWfX4nIgdnvlgHp9oWe+Z9+VTlpuuoHtvWM+EYmlqhLgpFEoc75CszU1PDO809TjvZVb7Gm2LQqir2r1us2H5hna35116G3hN9yn2XZ4xGWaoXh0PoSqnys9T/jUqlohqXnGKKb0aJR+K1y+2rb/EeovJPLTXCv4FTyiisCl4MDFdgE8OGc7YTeAsl2ohapN0TQ="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CHECK_CS=true
    - php: 7
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - travis_retry composer self-update
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0 ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then travis_retry curl -sSL https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh | bash ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then ./zf-mkdoc-theme/deploy.sh ; fi
