docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Services: services.md
    - Migration:
      - "Version 2 to Version 3": migration/v2-to-v3.md
site_name: zend-servicemanager-di
site_description: 'zend-servicemanager-di: zend-servicemanager / zend-di integration'
repo_url: 'https://github.com/zendframework/zend-servicemanager-di'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
