docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Services: services.md
    - Migration:
      - "Version 2 to Version 3": migration/v2-to-v3.md
site_name: zend-servicemanager-di
site_description: 'zend-di integration for zend-servicemanager'
repo_url: 'https://github.com/zendframework/zend-servicemanager-di'
extra:
  show_special_homepage: true
