docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Services: services.md
    - Migration:
      - "Version 2 to Version 3": migration/v2-to-v3.md
site_name: laminas-servicemanager-di
site_description: 'laminas-servicemanager-di: laminas-servicemanager / laminas-di integration'
repo_url: 'https://github.com/laminas/laminas-servicemanager-di'
